In [ ]:
# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:


import numpy as np
import pandas as pd
file=pd.read_csv('/content/drive/My Drive/CODING/fer2013.csv')
# test_file=pd.read_csv('/content/drive/My Drive/New folder/testck.csv')

print('file=',file)
# print('test_file=',test_file)

file=        emotion                                             pixels        Usage
0            0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...     Training
1            0  151 150 147 155 148 133 111 140 170 174 182 15...     Training
2            2  231 212 156 164 174 138 161 173 182 200 106 38...     Training
3            4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...     Training
4            6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...     Training
...        ...                                                ...          ...
35882        6  50 36 17 22 23 29 33 39 34 37 37 37 39 43 48 5...  PrivateTest
35883        3  178 174 172 173 181 188 191 194 196 199 200 20...  PrivateTest
35884        0  17 17 16 23 28 22 19 17 25 26 20 24 31 19 27 9...  PrivateTest
35885        3  30 28 28 29 31 30 42 68 79 81 77 67 67 71 63 6...  PrivateTest
35886        2  19 13 14 12 13 16 21 33 50 57 71 84 97 108 122...  PrivateTest

[35887 rows x 3 columns]


In [ ]:
file.shape[0]

35887

In [ ]:
#code to fetch all the data from imported csv files
#x and y
X=[]
Y=[]
for i in range(file.shape[0]):
  l=file.iloc[i,1].split()
  l=[float(ele) for ele in l] 
#   print('len=',len(l))
  print(i)
#   if file.iloc[i,2] == "Training":
  X.append(np.array(l).reshape(48,48))
  Y.append(file.iloc[i,0])

Streaming output truncated to the last 5000 lines.
30888
30889
30890
30891
30892
30893
30894
30895
30896
30897
30898
30899
30900
30901
30902
30903
30904
30905
30906
30907
30908
30909
30910
30911
30912
30913
30914
30915
30916
30917
30918
30919
30920
30921
30922
30923
30924
30925
30926
30927
30928
30929
30930
30931
30932
30933
30934
30935
30936
30937
30938
30939
30940
30941
30942
30943
30944
30945
30946
30947
30948
30949
30950
30951
30952
30953
30954
30955
30956
30957
30958
30959
30960
30961
30962
30963
30964
30965
30966
30967
30968
30969
30970
30971
30972
30973
30974
30975
30976
30977
30978
30979
30980
30981
30982
30983
30984
30985
30986
30987
30988
30989
30990
30991
30992
30993
30994
30995
30996
30997
30998
30999
31000
31001
31002
31003
31004
31005
31006
31007
31008
31009
31010
31011
31012
31013
31014
31015
31016
31017
31018
31019
31020
31021
31022
31023
31024
31025
31026
31027
31028
31029
31030
31031
31032
31033
31034
31035
31036
31037
31038
31039
31040
31041
31042
31043
31044
31045
3

In [ ]:


#printing the data X and Y and corresponding shape
X=np.asarray(X)
Y=np.asarray(Y)


print('X.shape=',X.shape)
print('Y.shape=',Y.shape)


X.shape= (35887, 48, 48)
Y.shape= (35887,)


In [ ]:
def normalize(x):
     # Normalize inputs to (0,1)
#     print(x.shape)
    print(x[0],x[1],x[2])
    x_n = x/255.
    return x_n
X = normalize(X)

[[ 70.  80.  82. ...  52.  43.  41.]
 [ 65.  61.  58. ...  56.  52.  44.]
 [ 50.  43.  54. ...  49.  56.  47.]
 ...
 [ 91.  65.  42. ...  72.  56.  43.]
 [ 77.  82.  79. ... 105.  70.  46.]
 [ 77.  72.  84. ... 106. 109.  82.]] [[151. 150. 147. ... 129. 140. 120.]
 [151. 149. 149. ... 122. 141. 137.]
 [151. 151. 156. ... 109. 123. 146.]
 ...
 [188. 188. 121. ... 185. 185. 186.]
 [188. 187. 196. ... 186. 182. 187.]
 [186. 184. 185. ... 193. 183. 184.]] [[231. 212. 156. ...  44.  27.  16.]
 [229. 175. 148. ...  27.  35.  27.]
 [214. 156. 157. ...  28.  22.  28.]
 ...
 [241. 245. 250. ...  57. 101. 146.]
 [246. 250. 252. ...  78. 105. 162.]
 [250. 251. 250. ...  88. 110. 152.]]


In [ ]:
#resahape image-pixels  inputs to classify to grayscale (3 ,if rgb)
def reshape(x):
    x_r=x.reshape(x.shape[0],x.shape[1],x.shape[2],1)
    print(x_r.shape)
    return x_r
X = reshape(X)

(35887, 48, 48, 1)


In [ ]:
#one hot encoding
def oneHot(y, Ny):
    
    from keras.utils import to_categorical 
    y_oh=to_categorical(y,num_classes=Ny)
    return y_oh
y_for_one_hot=Y

In [ ]:
y_one_hot_encoded = oneHot(y_for_one_hot,7)

Using TensorFlow backend.


In [ ]:

# splitting the whole data to train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y_one_hot_encoded, test_size=0.1,random_state=1)


In [ ]:
#give equal weightage to all the classes present in data
from sklearn.utils import class_weight
class_weights = class_weight.compute_class_weight('balanced', np.unique(y_train.argmax(1)), y_train.argmax(1))

In [ ]:
path = "/content/drive/My Drive/CODING/best_model_weights.hdf5"
from keras.models import load_model
loaded_model=load_model(path)

In [ ]:
loaded_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 44, 44, 64)        1664      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 20, 20, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 18, 18, 64)        36928     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 16, 16, 64)        36928     
_________________________________________________________________
average_pooling2d_1 (Average (None, 7, 7, 64)          0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 5, 5, 128)         73856     
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 3, 3, 128)        

In [ ]:
def accuracy(x_test, y_test, model):
    
    loss,acc=model.evaluate(x_test,y_test,verbose=0)
    return acc

acc = accuracy(x_test, y_test, loaded_model)
print('Test accuracy is, ', acc*100, '%')

Test accuracy is,  58.12203884124756 %


In [ ]:
def oneHot_tolabel(y):
    
    y_b = np.argmax(y,axis=1)
    np.asarray(y_b)
    return y_b

def predict(x):
    
    y=loaded_model.predict(x)
    return y

y_pred=predict(x_train)
y_pre=predict(x_test)

In [ ]:
def create_confusion_matrix(true_labels, predicted_labels):
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_train.argmax(axis=1), y_pred.argmax(axis=1))
    return cm

# cm = create_confusion_matrix(train_labels,predict(train_samples))
cm_for_training = create_confusion_matrix(oneHot_tolabel(y_train), oneHot_tolabel(y_pred))
# cm_test=create_confusion_matrix(oneHot_tolabel(y_test),oneHot_tolabel(predict(x_train)))

In [ ]:
# confusion matrix for training
cm_for_training

array([[2111,   29,  331,  330,  932,  148,  595],
       [ 202,   74,   68,   21,  104,   13,   17],
       [ 537,    6, 1145,  323, 1330,  713,  561],
       [ 160,    1,  157, 6707,  507,  172,  341],
       [ 484,    5,  302,  436, 3093,   83, 1092],
       [  84,    0,  268,  216,  107, 2826,  108],
       [ 322,    6,  179,  540, 1101,  113, 3298]])

In [ ]:
def create_confusion_matrix(true_labels, predicted_labels):
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test.argmax(axis=1), y_pre.argmax(axis=1))
    return cm

# cm = create_confusion_matrix(train_labels,predict(train_samples))
cm_for_test = create_confusion_matrix(oneHot_tolabel(y_test), oneHot_tolabel(y_pre))

In [ ]:
# confusion matrix for testing
cm_for_test

array([[232,   2,  42,  36,  86,  13,  66],
       [ 17,   8,   9,   2,   8,   0,   4],
       [ 66,   1, 115,  35, 152,  74,  63],
       [ 18,   0,  17, 775,  72,  24,  38],
       [ 71,   0,  32,  44, 313,   9, 113],
       [ 12,   0,  39,  27,  11, 285,  19],
       [ 40,   0,  23,  79, 126,  13, 358]])